[package]
name = "minimessage"
version = "0.1.0"
edition = "2024"

[dependencies]
minimessage-impl = { path = "./minimessage-impl" }
minimessage-macro = { path = "./minimessage-macro" }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "parser"
harness = false

[workspace]
members = [
    "minimessage-macro",
    "macro_test", "minimessage-impl",
]
